/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import agencia.de.turismo.Alojamiento;
import agencia.de.turismo.AlojamientoData;
import agencia.de.turismo.Cliente;
import agencia.de.turismo.ClienteData;
import agencia.de.turismo.Compra;
import agencia.de.turismo.CompraData;
import agencia.de.turismo.Conexion;
import agencia.de.turismo.Paquete;
import agencia.de.turismo.PaqueteData;
import agencia.de.turismo.Traslado;
import agencia.de.turismo.TrasladoData;
import java.util.List;

/**
 *
 * @author Familia
 */
public class CompraAgregar extends javax.swing.JInternalFrame {
    public int modo;
    public int id;
    
    /**
     * Creates new form CompraAgregar
     */
    public CompraAgregar(int id, int modo, int cantidadDePasajeros) {
        initComponents();
        this.id = id;
        this.modo = modo;
        if(modo == 2) {
                btn_Aceptar.setText("Actualizar");
            }
        try {
        
            Conexion con = new Conexion("jdbc:mysql://localhost/agenciadeturismo", "root", ""); 
              TrasladoData pd = new TrasladoData(con);
            List<Traslado> listaTraslado = pd.listadoTraslado(); 
            PaqueteData paquete = new PaqueteData(con);
            CompraData comprad = new CompraData(con);
            Compra compraCompleta = null;
            Paquete paqueteCompleto = null;
            if(modo == 2) {
                compraCompleta = comprad.consultarCompra(id);
                paqueteCompleto = paquete.consultarPaquete(compraCompleta.getPaquete().getId());
                casilla_pasajeros.setValue(cantidadDePasajeros);
            }
            for (int i = 0; i < listaTraslado.size(); i++) { 
                //cmb_traslado.addItem(listaTraslado.get(i).getTipoDeTransporte() + " " + listaTraslado.get(i).getPatente() + " " + listaTraslado.get(i).getCantidadMaximaDePasajeros());
                cmb_traslado.addItem(listaTraslado.get(i));
                if(modo == 2 && listaTraslado.get(i).getId() == paqueteCompleto.getTraslado().getId()) {
                    cmb_traslado.setSelectedItem(listaTraslado.get(i));
                }
            }
            AlojamientoData ad = new AlojamientoData(con);
            List<Alojamiento> listaAlojamiento = ad.listadoAlojamiento(); 
            
            for (int i = 0; i < listaAlojamiento.size(); i++) { 
                cmb_alojamiento.addItem(listaAlojamiento.get(i));
                if(modo == 2 && listaAlojamiento.get(i).getId() == paqueteCompleto.getAlojamiento().getId()) {
                    cmb_alojamiento.setSelectedItem(listaAlojamiento.get(i));
                }
            }
            ClienteData cd = new ClienteData(con);
            List<Cliente> listaCliente = cd.listadoClientes();
            for (int i = 0; i < listaCliente.size(); i++) { 
                cmb_cliente.addItem(listaCliente.get(i));
                if(modo == 2 && listaCliente.get(i).getId() == compraCompleta.getCliente().getId()) {
                    cmb_cliente.setSelectedItem(listaCliente.get(i));
                }
            }
            
            }
         catch(Exception ex) {
           System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmb_cliente = new javax.swing.JComboBox<>();
        cmb_alojamiento = new javax.swing.JComboBox<>();
        cmb_traslado = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        casilla_pasajeros = new javax.swing.JSpinner();
        btn_Aceptar = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();

        jLabel1.setText("Cliente");

        cmb_alojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_alojamientoActionPerformed(evt);
            }
        });

        jLabel2.setText("Alojamiento");

        jLabel3.setText("Traslado");

        jLabel4.setText("Pasajeros");

        btn_Aceptar.setText("Agregar");
        btn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AceptarActionPerformed(evt);
            }
        });

        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmb_traslado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_alojamiento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_cliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(casilla_pasajeros, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Aceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(196, 196, 196))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_alojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmb_traslado, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla_pasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btn_Aceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_alojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_alojamientoActionPerformed
        cmb_traslado.removeAllItems();
        try {
            Conexion con = new Conexion("jdbc:mysql://localhost/agenciadeturismo", "root", ""); 
            PaqueteData pd = new PaqueteData(con);
            Alojamiento alo = (Alojamiento) cmb_alojamiento.getSelectedItem();
            List<Traslado> listaTraslados = pd.listadoTrasladoPorAlojamiento(alo.getId());
            for (int i = 0; i < listaTraslados.size(); i++) { 
                //cmb_traslado.addItem(listaTraslado.get(i).getTipoDeTransporte() + " " + listaTraslado.get(i).getPatente() + " " + listaTraslado.get(i).getCantidadMaximaDePasajeros());
                cmb_traslado.addItem(listaTraslados.get(i));
                
            }
         } catch(Exception ex) { 
            System.out.println(ex.getMessage());
        }
         
    }//GEN-LAST:event_cmb_alojamientoActionPerformed

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_CancelarActionPerformed

    private void btn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AceptarActionPerformed
        if(modo == 1) {
            try {
        
            Conexion con = new Conexion("jdbc:mysql://localhost/agenciadeturismo", "root", ""); 
              CompraData pd = new CompraData(con);
              Compra p = new Compra();
              Cliente tra = (Cliente) cmb_cliente.getSelectedItem();
              Traslado traslado = (Traslado) cmb_traslado.getSelectedItem();
              Alojamiento alo = (Alojamiento) cmb_alojamiento.getSelectedItem();
              PaqueteData a = new PaqueteData(con);
              a.paquetePorAlojamientoTraslado(alo.getId(), traslado.getId());
              p.setCliente(tra);
              p.setPaquete(a.paquetePorAlojamientoTraslado(alo.getId(), traslado.getId()));
              p.setCantidadDePasajeros((int)casilla_pasajeros.getValue());
              pd.agregarCompra(p);
              this.dispose();
      } catch(Exception ex) { 
          System.out.println(ex.getMessage());
      }
        }
        if(modo == 2) {
            try {
        
            Conexion con = new Conexion("jdbc:mysql://localhost/agenciadeturismo", "root", ""); 
              CompraData pd = new CompraData(con);
              Compra p = new Compra();
              Cliente tra = (Cliente) cmb_cliente.getSelectedItem();
              Traslado traslado = (Traslado) cmb_traslado.getSelectedItem();
              Alojamiento alo = (Alojamiento) cmb_alojamiento.getSelectedItem();
              PaqueteData a = new PaqueteData(con);
              ;
              p.setId(id);
              pd.actualizarCompra(p, tra, a.paquetePorAlojamientoTraslado(alo.getId(), traslado.getId()), (int)casilla_pasajeros.getValue());
              this.dispose();
      } catch(Exception ex) { 
          System.out.println(ex.getMessage());
      }
        }
    }//GEN-LAST:event_btn_AceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Aceptar;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JSpinner casilla_pasajeros;
    private javax.swing.JComboBox<Alojamiento> cmb_alojamiento;
    private javax.swing.JComboBox<Cliente> cmb_cliente;
    private javax.swing.JComboBox<Traslado> cmb_traslado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
