/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import agencia.de.turismo.Conexion;
import agencia.de.turismo.Paquete;
import agencia.de.turismo.PaqueteData;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Familia
 */
public class ListaPaquete extends javax.swing.JInternalFrame {
   private DefaultTableModel modelo;
     public JDesktopPane escritorio;
    /**
     * Creates new form ListaPaquete
     */
    public ListaPaquete() {
        initComponents();
         try {
            Conexion con = new Conexion("jdbc:mysql://localhost/agenciadeturismo", "root", ""); 
            PaqueteData pd = new PaqueteData(con);
            List<Paquete> listaPaquete = pd.listadoPaquete();
             modelo = (DefaultTableModel) tb_paquetes.getModel();
            tb_paquetes.setDefaultRenderer(Object.class, new Render());

            
            modelo.setRowCount(0);
            Object[] fila = new Object[modelo.getColumnCount()];

            for (int i = 0; i < listaPaquete.size(); i++) {
                fila[0] = listaPaquete.get(i).getId();
                fila[1] = listaPaquete.get(i).getTraslado().getPatente();
                fila[2] = listaPaquete.get(i).getTraslado().getTipoDeTransporte();
                fila[3] = listaPaquete.get(i).getAlojamiento().getDireccion();
                JButton btnBorrar = new JButton();
                btnBorrar.setText("Borrar");
                fila[4] = btnBorrar;
               
                JButton btnActualizar = new JButton();
                btnActualizar.setText("Actualizar");
                fila[5] = btnActualizar;
                
                modelo.addRow(fila);
            }
        } catch(Exception ex) {
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_paquetes = new javax.swing.JTable();
        btn_agregar = new javax.swing.JButton();

        tb_paquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "patente del transporte", "tipo de transporte", "direccion del alojamiento", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_paquetes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_paquetesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_paquetes);
        if (tb_paquetes.getColumnModel().getColumnCount() > 0) {
            tb_paquetes.getColumnModel().getColumn(0).setResizable(false);
            tb_paquetes.getColumnModel().getColumn(1).setResizable(false);
            tb_paquetes.getColumnModel().getColumn(2).setResizable(false);
            tb_paquetes.getColumnModel().getColumn(3).setResizable(false);
            tb_paquetes.getColumnModel().getColumn(4).setResizable(false);
            tb_paquetes.getColumnModel().getColumn(5).setResizable(false);
        }

        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_agregar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_agregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        // TODO add your handling code here:
      PaquetesAgregar frmAgregar = new PaquetesAgregar();
        escritorio.removeAll();
        escritorio.repaint();
        frmAgregar.setVisible(true);
      frmAgregar.modo = 1;
        escritorio.add(frmAgregar).setSize(400, 400);
        escritorio.moveToFront(frmAgregar);
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void tb_paquetesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_paquetesMouseClicked
        int column = tb_paquetes.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/tb_paquetes.getRowHeight();
        
        if(column == 4) {
            AvisoBorrarPaquete avisoBorrar = new AvisoBorrarPaquete();
        escritorio.removeAll();
        escritorio.repaint();
        avisoBorrar.setVisible(true);
        
        avisoBorrar.id = (int)tb_paquetes.getValueAt(row, 0);
       
        escritorio.add(avisoBorrar).setSize(400, 400);
        escritorio.moveToFront(avisoBorrar);
        
        } 
        if(column == 5) {
          PaquetesAgregar frmAgregar = new PaquetesAgregar();
        escritorio.removeAll();
        escritorio.repaint();
        frmAgregar.setVisible(true);
      frmAgregar.modo = 2;
      frmAgregar.id = (int)tb_paquetes.getValueAt(row, 0);
        escritorio.add(frmAgregar).setSize(400, 400);
        escritorio.moveToFront(frmAgregar);   
        }
            
        
    }//GEN-LAST:event_tb_paquetesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_paquetes;
    // End of variables declaration//GEN-END:variables
}
