/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import agencia.de.turismo.Alojamiento;
import agencia.de.turismo.AlojamientoData;
import agencia.de.turismo.Conexion;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author epda
 */
public class ListaAlojamiento2 extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo;
     public JDesktopPane escritorio;
    /**
     * Creates new form ListaAlojamiento2
     */
    public ListaAlojamiento2() {
        initComponents();
        try {
            Conexion con = new Conexion("jdbc:mysql://localhost/agenciadeturismo", "root", ""); 
            AlojamientoData ad = new AlojamientoData(con);
            List<Alojamiento> listaAlojamiento = ad.listadoAlojamiento();
             modelo = (DefaultTableModel)tb_alojamiento.getModel();
            tb_alojamiento.setDefaultRenderer(Object.class, new Render());

            
            modelo.setRowCount(0);
            Object[] fila = new Object[modelo.getColumnCount()];

            for (int i = 0; i < listaAlojamiento.size(); i++) {
                fila[0] = listaAlojamiento.get(i).getId();
                fila[1] = listaAlojamiento.get(i).getDireccion();
                fila[2] = listaAlojamiento.get(i).getCapacidad();
                fila[3] = listaAlojamiento.get(i).getCostoPorNoche();
                fila[4] = listaAlojamiento.get(i).boolASiNo(listaAlojamiento.get(i).isAdmiteFumadores());
                fila[5] = listaAlojamiento.get(i).getTipo_de_alojamiento();
                JButton btnBorrar = new JButton();
                btnBorrar.setText("Borrar");
                fila[6] = btnBorrar;
               
                JButton btnActualizar = new JButton();
                btnActualizar.setText("Actualizar");
                fila[7] = btnActualizar;
               
                
                modelo.addRow(fila);
            }
        } catch(ClassNotFoundException ex) {
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_alojamiento = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(800, 400));

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tb_alojamiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Direccion", "Capacidad", "Costo por noche", "Admite fumadores", "Tipo de alojamiento", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_alojamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_alojamientoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tb_alojamiento);
        if (tb_alojamiento.getColumnModel().getColumnCount() > 0) {
            tb_alojamiento.getColumnModel().getColumn(0).setResizable(false);
            tb_alojamiento.getColumnModel().getColumn(1).setResizable(false);
            tb_alojamiento.getColumnModel().getColumn(2).setResizable(false);
            tb_alojamiento.getColumnModel().getColumn(3).setResizable(false);
            tb_alojamiento.getColumnModel().getColumn(4).setResizable(false);
            tb_alojamiento.getColumnModel().getColumn(5).setResizable(false);
            tb_alojamiento.getColumnModel().getColumn(6).setResizable(false);
            tb_alojamiento.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(0, 878, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      escritorio.removeAll();
        escritorio.repaint();
        AlojamientoAgregar lc = new AlojamientoAgregar();
        lc.escritorio = escritorio;
        lc.setVisible(true);
         escritorio.add(lc).setSize(300, 275);
        escritorio.moveToFront(lc);
        lc.modo = 1;
                                       
    }//GEN-LAST:event_jButton2ActionPerformed
 public boolean SiONoABool(String a) {
         if(a == "Si") {
             return true;
         } else {
             return false;
         }
     }
    private void tb_alojamientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_alojamientoMouseClicked
          int column = tb_alojamiento.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/tb_alojamiento.getRowHeight();
        
        if(column == 6) {
            AvisoBorrarA avisoBorrar = new AvisoBorrarA();
        escritorio.removeAll();
        escritorio.repaint();
        avisoBorrar.setVisible(true);
    
        AvisoBorrarA.id = (int) tb_alojamiento.getValueAt(row, 0);
       
        escritorio.add(avisoBorrar).setSize(270, 125);
        escritorio.moveToFront(avisoBorrar);
        } 
        
        
        if(column == 7) {
        int id = (int)tb_alojamiento.getValueAt(row, 0);
        String direccion = (String)tb_alojamiento.getValueAt(row, 1);
        int capacidad = (int)tb_alojamiento.getValueAt(row, 2);
        int costopornoches = (int)tb_alojamiento.getValueAt(row, 3);
        boolean fumadores = (boolean)SiONoABool((String)tb_alojamiento.getValueAt(row, 4));
        String tipo = (String)tb_alojamiento.getValueAt(row, 5);
        
        AlojamientoAgregar frmAgregar = new AlojamientoAgregar(2, id, capacidad, costopornoches, fumadores, direccion, tipo);
        
        frmAgregar.id = (int)tb_alojamiento.getValueAt(row, 0);
        frmAgregar.direccion = (String)tb_alojamiento.getValueAt(row, 1);
        frmAgregar.capacidad = (int)tb_alojamiento.getValueAt(row, 2);
        frmAgregar.costepornoche = (int)tb_alojamiento.getValueAt(row, 3);
        frmAgregar.admitefumadores = (boolean)SiONoABool((String)tb_alojamiento.getValueAt(row, 4));
        frmAgregar.tipo = (String)tb_alojamiento.getValueAt(row, 5);
        escritorio.removeAll(); 
        escritorio.repaint();
        frmAgregar.setVisible(true);
        escritorio.add(frmAgregar).setSize(300, 275);
        escritorio.moveToFront(frmAgregar);
        
        }
    }//GEN-LAST:event_tb_alojamientoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tb_alojamiento;
    // End of variables declaration//GEN-END:variables
}
