/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import agencia.de.turismo.Alojamiento;
import agencia.de.turismo.AlojamientoData;

import agencia.de.turismo.Conexion;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class ListaAlojamiento extends javax.swing.JInternalFrame {
   private DefaultTableModel modelo;
     public JDesktopPane escritorio;
    /**
     * Creates new form ListaClientes
     */
    public ListaAlojamiento() {
      initComponents();
      
        try {
            Conexion con = new Conexion("jdbc:mysql://localhost/asdawawe", "root", ""); 
            AlojamientoData ad = new AlojamientoData(con);
            List<Alojamiento> listaAlojamiento = ad.listadoAlojamiento();
             modelo = (DefaultTableModel)tb_alojamiento.getModel();
            tb_alojamiento.setDefaultRenderer(Object.class, new Render());

            
            modelo.setRowCount(0);
            Object[] fila = new Object[modelo.getColumnCount()];

            for (int i = 0; i < listaAlojamiento.size(); i++) {
                fila[0] = listaAlojamiento.get(i).getId();
                fila[1] = listaAlojamiento.get(i).getCapacidad();
                fila[2] = listaAlojamiento.get(i).getCostoPorNoche();
                fila[3] = listaAlojamiento.get(i).isAdmiteFumadores();
                fila[4] = listaAlojamiento.get(i).getDireccion();
                JButton btnBorrar = new JButton();
                btnBorrar.setText("Borrar");
                fila[5] = btnBorrar;
               
                JButton btnActualizar = new JButton();
                btnActualizar.setText("Actualizar");
                fila[6] = btnActualizar;
               
                
                modelo.addRow(fila);
            }
        } catch(ClassNotFoundException ex) {
            System.out.println(ex.getMessage());
        }
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   

    private void tb_alojamientoMouseClicked(java.awt.event.MouseEvent evt) {                                        
        int column = tb_alojamiento.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/tb_alojamiento.getRowHeight();
        
        if(column == 5) {
            AvisoBorrar avisoBorrar = new AvisoBorrar();
        escritorio.removeAll();
        escritorio.repaint();
        avisoBorrar.setVisible(true);
        
        avisoBorrar.id = (int)tb_alojamiento.getValueAt(row, 0);
       
        escritorio.add(avisoBorrar).setSize(400, 400);
        escritorio.moveToFront(avisoBorrar);
        
        }
        if(column == 6) {
        int id = (int)tb_alojamiento.getValueAt(row, 0);
        String direccion = (String)tb_alojamiento.getValueAt(row, 1);
        int capacidad = (int)tb_alojamiento.getValueAt(row, 2);
        int costepornoche = (int)tb_alojamiento.getValueAt(row, 3);
        boolean admitefumadores = (boolean)tb_alojamiento.getValueAt(row, 4);
        
        AlojamientoAgregar frmAgregar = new AlojamientoAgregar(id,capacidad,costepornoche,admitefumadores,direccion);
        escritorio.removeAll();
        escritorio.repaint();
        frmAgregar.setVisible(true);
        frmAgregar.modo = 2;
        frmAgregar.id = (int)tb_alojamiento.getValueAt(row, 0);
        frmAgregar.capacidad = (int) tb_alojamiento.getValueAt(row, 1);
        frmAgregar.costepornoche = (int) tb_alojamiento.getValueAt(row, 2);
        frmAgregar.admitefumadores = (boolean) tb_alojamiento.getValueAt(row, 3);
        escritorio.add(frmAgregar).setSize(400, 400);
        escritorio.moveToFront(frmAgregar);
        }
        
    }                                       

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        AlojamientoAgregar frmAgregar = new AlojamientoAgregar();
        escritorio.removeAll();
        escritorio.repaint();
        frmAgregar.setVisible(true);
        frmAgregar.modo = 1;
        escritorio.add(frmAgregar).setSize(400, 400);
        escritorio.moveToFront(frmAgregar);
    }                                        


  
     
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        entityManager1 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory(null).createEntityManager();
        jFrame4 = new javax.swing.JFrame();
        jFrame5 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_alojamiento = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("jButton1");
        jScrollPane1.setViewportView(jButton1);

        tb_alojamiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "DIRECCION", "CAPACIDAD", "COSTE_POR_NOCHE", "FUMADORES", "", ""
            }
        ));
        jScrollPane3.setViewportView(tb_alojamiento);

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        


    // Variables declaration - do not modify                     
    private javax.persistence.EntityManager entityManager1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JFrame jFrame5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tb_alojamiento;
    // End of variables declaration                   
}
