/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import agencia.de.turismo.Alojamiento;
import agencia.de.turismo.AlojamientoData;
import agencia.de.turismo.Conexion;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author epda
 */
public class ListaAlojamiento2 extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo;
     public JDesktopPane escritorio;
    /**
     * Creates new form ListaAlojamiento2
     */
    public ListaAlojamiento2() {
        initComponents();
        try {
            Conexion con = new Conexion("jdbc:mysql://localhost/asdawawe", "root", ""); 
            AlojamientoData ad = new AlojamientoData(con);
            List<Alojamiento> listaAlojamiento = ad.listadoAlojamiento();
             modelo = (DefaultTableModel)tb_alojamiento.getModel();
            tb_alojamiento.setDefaultRenderer(Object.class, new Render());

            
            modelo.setRowCount(0);
            Object[] fila = new Object[modelo.getColumnCount()];

            for (int i = 0; i < listaAlojamiento.size(); i++) {
                fila[0] = listaAlojamiento.get(i).getId();
                fila[1] = listaAlojamiento.get(i).getDireccion();
                fila[2] = listaAlojamiento.get(i).getCapacidad();
                fila[3] = listaAlojamiento.get(i).getCostoPorNoche();
                fila[4] = listaAlojamiento.get(i).getAdmiteFumadores();
                fila[5] = listaAlojamiento.get(i).getTipoDeAlojamiento();
                JButton btnBorrar = new JButton();
                btnBorrar.setText("Borrar");
                fila[6] = btnBorrar;
               
                JButton btnActualizar = new JButton();
                btnActualizar.setText("Actualizar");
                fila[7] = btnActualizar;
               
                
                modelo.addRow(fila);
            }
        } catch(ClassNotFoundException ex) {
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_alojamiento = new javax.swing.JTable();

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tb_alojamiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "DIRECCION", "CAPACIDAD", "COSTE_POR_NOCHE", "FUMADORES", "TIPO_DE_ALOJAMIENTO", "", ""
            }
        ));
        tb_alojamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_alojamientoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tb_alojamiento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      escritorio.removeAll();
        escritorio.repaint();
        AlojamientoAgregar lc = new AlojamientoAgregar();
        lc.escritorio = escritorio;
        lc.setVisible(true);
         escritorio.add(lc).setSize(600, 400);
        escritorio.moveToFront(lc);
        lc.modo = 1;
                                       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tb_alojamientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_alojamientoMouseClicked
          int column = tb_alojamiento.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/tb_alojamiento.getRowHeight();
        
       /* if(column == 6) {
            AvisoBorrarA avisoBorrar = new AvisoBorrarA();
        escritorio.removeAll();
        escritorio.repaint();
        avisoBorrar.setVisible(true);
    
        avisoBorrar.id = (int)tb_alojamiento.getValueAt(row, 0);
       
        escritorio.add(avisoBorrar).setSize(400, 400);
        escritorio.moveToFront(avisoBorrar);} */
        
        
        if(column == 7) {
        int id = (int)tb_alojamiento.getValueAt(row, 0);
        String direccion = (String)tb_alojamiento.getValueAt(row, 1);
        int capacidad = (int)tb_alojamiento.getValueAt(row, 2);
        int costopornoches = (int)tb_alojamiento.getValueAt(row, 3);
        int fumadores = (int)tb_alojamiento.getValueAt(row, 4);
        String tipoDeTransporte = (String)tb_alojamiento.getValueAt(row, 5);
        
        AlojamientoAgregar frmAgregar = new AlojamientoAgregar();
        escritorio.removeAll();
       
        
        frmAgregar.setVisible(true);
        frmAgregar.modo = 2;
        
        frmAgregar.id = (int)tb_alojamiento.getValueAt(row, 0);
         frmAgregar.direccion = (String)tb_alojamiento.getValueAt(row, 1);
         frmAgregar.capacidad = (int)tb_alojamiento.getValueAt(row, 2);
        frmAgregar.costepornoche = (int)tb_alojamiento.getValueAt(row, 3);
        frmAgregar.admitefumadores = (int)tb_alojamiento.getValueAt(row, 4);
        frmAgregar.tipo = (String) tb_alojamiento.getValueAt(row, 5);
        escritorio.add(frmAgregar);
                frmAgregar.setSize(400, 400);
        escritorio.moveToFront(frmAgregar);
        escritorio.repaint();
        }
    }//GEN-LAST:event_tb_alojamientoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tb_alojamiento;
    // End of variables declaration//GEN-END:variables
}
